/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.Cursor;
import logica.BLLUsuario;

/**
 *
 * @author ArcosArce
 */
public class panPaso1 extends javax.swing.JPanel {

    /**
     * Creates new form panPaso1
     */
    private FrmRegistro parent;
    private static final String PLACEHOLDER_PASSWORD = "Contraseña";
    private static final String PLACEHOLDER_CONFIRM = "Confirmar contraseña";
    private static final Color COLOR_PLACEHOLDER = new Color(153, 153, 153);
    private static final Color COLOR_TEXTO = new Color(255, 255, 255);

    public panPaso1(FrmRegistro parent) {
        this.parent = parent;
        initComponents();
        configurarPlaceholders();
        actualizarProgressBar();
    }
    
    private void actualizarProgressBar() {
        pgbProgreso.setValue(50);
        pgbProgreso.setEnabled(false); // Desactiva interacción
        pgbProgreso.setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); // Cursor normal
    }
    
    private void configurarPlaceholders() {
        // Placeholder para contraseña
        txtPassword.setEchoChar((char) 0);
        txtPassword.setText(PLACEHOLDER_PASSWORD);
        txtPassword.setForeground(COLOR_PLACEHOLDER);

        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (String.valueOf(txtPassword.getPassword()).equals(PLACEHOLDER_PASSWORD)) {
                    txtPassword.setText("");
                    txtPassword.setForeground(COLOR_TEXTO);
                    txtPassword.setEchoChar('•');
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (String.valueOf(txtPassword.getPassword()).trim().isEmpty()) {
                    txtPassword.setEchoChar((char) 0);
                    txtPassword.setText(PLACEHOLDER_PASSWORD);
                    txtPassword.setForeground(COLOR_PLACEHOLDER);
                }
            }
        });

        // Placeholder para confirmar contraseña
        txtConfirmarPassword.setEchoChar((char) 0);
        txtConfirmarPassword.setText(PLACEHOLDER_CONFIRM);
        txtConfirmarPassword.setForeground(COLOR_PLACEHOLDER);

        txtConfirmarPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (String.valueOf(txtConfirmarPassword.getPassword()).equals(PLACEHOLDER_CONFIRM)) {
                    txtConfirmarPassword.setText("");
                    txtConfirmarPassword.setForeground(COLOR_TEXTO);
                    txtConfirmarPassword.setEchoChar('•');
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (String.valueOf(txtConfirmarPassword.getPassword()).trim().isEmpty()) {
                    txtConfirmarPassword.setEchoChar((char) 0);
                    txtConfirmarPassword.setText(PLACEHOLDER_CONFIRM);
                    txtConfirmarPassword.setForeground(COLOR_PLACEHOLDER);
                }
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgbProgreso = new ProgressBarPersonalizada();
        btnVolver = new BotonPersonalizado(new java.awt.Color(20,20,20));
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnSiguiente = new BotonPersonalizado(new java.awt.Color(29,184,85));
        txtConfirmarPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(20, 20, 20));

        pgbProgreso.setBackground(new java.awt.Color(204, 204, 204));
        pgbProgreso.setForeground(new java.awt.Color(29, 184, 85));

        btnVolver.setBackground(new java.awt.Color(20, 20, 20));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver-arriba-removebg-preview.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Paso 1 de 2");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Crea una contraseña");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña");

        txtPassword.setBackground(new java.awt.Color(20, 20, 20));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("jPasswordField1");

        btnSiguiente.setBackground(new java.awt.Color(29, 184, 85));
        btnSiguiente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        txtConfirmarPassword.setBackground(new java.awt.Color(20, 20, 20));
        txtConfirmarPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmarPassword.setText("jPasswordField1");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirma contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgbProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtPassword)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(txtConfirmarPassword))))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(pgbProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        String password = new String(txtPassword.getPassword());
        String confirmar = new String(txtConfirmarPassword.getPassword());

        // Solo validar que no estén vacíos ni sean placeholders
        if (password.isEmpty() || password.equals(PLACEHOLDER_PASSWORD)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Ingrese una contraseña");
            return;
        }

        if (confirmar.isEmpty() || confirmar.equals(PLACEHOLDER_CONFIRM)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Confirme su contraseña");
            return;
        }

        if (!password.equals(confirmar)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Las contraseñas no coinciden");
            return;
        }

        if(BLLUsuario.validarContraseña(password)){
            parent.getDatosRegistro().setPassword(password);
            parent.getDatosRegistro().setConfirmarPassword(confirmar);
            parent.avanzarPaso("paso1");
        }
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        parent.retrocederPaso();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar pgbProgreso;
    private javax.swing.JPasswordField txtConfirmarPassword;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
