/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.Cursor;
import java.time.LocalDate;
import logica.BLLUsuario;
import presentacion.BotonPersonalizado;
import presentacion.FrmRegistro;
import presentacion.ProgressBarPersonalizada;

/**
 *
 * @author ArcosArce
 */
public class panPaso2 extends javax.swing.JPanel {

    /**
     * Creates new form panPaso1
     */
    private FrmRegistro parent;
    private static final String PLACEHOLDER_DIA = "dd";
    private static final String PLACEHOLDER_AÑO = "aaaa";
    private static final Color COLOR_PLACEHOLDER = new Color(153, 153, 153);
    private static final Color COLOR_TEXTO = new Color(255, 255, 255);
    
    public panPaso2(FrmRegistro parent) {
        this.parent = parent;
        initComponents();
        cargarMeses();
        configurarPlaceholders(); // AGREGAR
        actualizarProgressBar(); // AGREGAR
    }
    
    private void actualizarProgressBar() {
        pgbProgreso.setValue(100);
        pgbProgreso.setEnabled(false);
        pgbProgreso.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
    
    private void configurarPlaceholders() {
        // Placeholder para día
        txtDia.setText(PLACEHOLDER_DIA);
        txtDia.setForeground(COLOR_PLACEHOLDER);

        txtDia.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtDia.getText().equals(PLACEHOLDER_DIA)) {
                    txtDia.setText("");
                    txtDia.setForeground(COLOR_TEXTO);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtDia.getText().trim().isEmpty()) {
                    txtDia.setText(PLACEHOLDER_DIA);
                    txtDia.setForeground(COLOR_PLACEHOLDER);
                }
            }
        });

        // Placeholder para año
        txtAño.setText(PLACEHOLDER_AÑO);
        txtAño.setForeground(COLOR_PLACEHOLDER);

        txtAño.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtAño.getText().equals(PLACEHOLDER_AÑO)) {
                    txtAño.setText("");
                    txtAño.setForeground(COLOR_TEXTO);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtAño.getText().trim().isEmpty()) {
                    txtAño.setText(PLACEHOLDER_AÑO);
                    txtAño.setForeground(COLOR_PLACEHOLDER);
                }
            }
        });

        // Placeholder para nombre
        txtNombre.setForeground(COLOR_TEXTO);
    }
    
    private void cargarMeses() {
        cmbMes.removeAllItems();
        cmbMes.addItem("Mes"); // Opción por defecto
        String[] meses = {
            "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
            "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
        };
        for (String mes : meses) {
            cmbMes.addItem(mes);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGenero = new javax.swing.ButtonGroup();
        pgbProgreso = new ProgressBarPersonalizada();
        btnVolver = new BotonPersonalizado(new java.awt.Color(20,20,20));
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new BotonPersonalizado(new java.awt.Color(29,184,85));
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        cmbMes = new javax.swing.JComboBox<>();
        txtAño = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jrbHombre = new javax.swing.JRadioButton();
        jrbOtro = new javax.swing.JRadioButton();
        jrbMujer = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(20, 20, 20));

        btnVolver.setBackground(new java.awt.Color(20, 20, 20));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver-arriba-removebg-preview.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Paso 2 de 2");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Háblanos de ti");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        btnRegistrar.setBackground(new java.awt.Color(29, 184, 85));
        btnRegistrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRegistrar.setText("Regístrate");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Este nombre aparecerá en tu perfil");

        txtNombre.setBackground(new java.awt.Color(20, 20, 20));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de nacimiento");

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("¿Por qué necesitamos tu fecha de nacimiento?");

        txtDia.setBackground(new java.awt.Color(20, 20, 20));
        txtDia.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtDia.setForeground(new java.awt.Color(255, 255, 255));
        txtDia.setText("dd");

        cmbMes.setBackground(new java.awt.Color(20, 20, 20));
        cmbMes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cmbMes.setForeground(new java.awt.Color(255, 255, 255));
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes" }));

        txtAño.setBackground(new java.awt.Color(20, 20, 20));
        txtAño.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtAño.setForeground(new java.awt.Color(255, 255, 255));
        txtAño.setText("aaaa");

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Usamos tu género para personalizar nuestras ");

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Género");

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("recomendaciones de contenido y los anuncios.");

        btgGenero.add(jrbHombre);
        jrbHombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jrbHombre.setForeground(new java.awt.Color(255, 255, 255));
        jrbHombre.setText("Hombre");

        btgGenero.add(jrbOtro);
        jrbOtro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jrbOtro.setForeground(new java.awt.Color(255, 255, 255));
        jrbOtro.setText("Otro");

        btgGenero.add(jrbMujer);
        jrbMujer.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jrbMujer.setForeground(new java.awt.Color(255, 255, 255));
        jrbMujer.setText("Mujer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgbProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jrbHombre)
                                    .addGap(40, 40, 40)
                                    .addComponent(jrbMujer)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jrbOtro))
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(cmbMes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(pgbProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDia)
                    .addComponent(cmbMes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbHombre)
                    .addComponent(jrbOtro)
                    .addComponent(jrbMujer))
                .addGap(30, 30, 30)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombre = txtNombre.getText().trim();
        String diaStr = txtDia.getText().trim();
        String mesStr = cmbMes.getSelectedItem().toString();
        String anioStr = txtAño.getText().trim();

        // Solo validar que no estén vacíos
        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese su nombre");
            return;
        }

        if (diaStr.equals(PLACEHOLDER_DIA) || anioStr.equals(PLACEHOLDER_AÑO)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Complete su fecha de nacimiento");
            return;
        }

        if (mesStr.equals("Mes")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Seleccione un mes");
            return;
        }

        try {
            int dia = Integer.parseInt(diaStr);
            int anio = Integer.parseInt(anioStr);
            int mes = cmbMes.getSelectedIndex();

            java.time.LocalDate fechaNacimiento = java.time.LocalDate.of(anio, mes, dia);

            String genero = null;
            if (jrbHombre.isSelected()) genero = "Masculino";
            else if (jrbMujer.isSelected()) genero = "Femenino";
            else if (jrbOtro.isSelected()) genero = "Otro";

            if (genero == null) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Seleccione un género");
                return;
            }

            if(BLLUsuario.validarDatosRegistro(nombre, fechaNacimiento, genero)){
                parent.getDatosRegistro().setNombre(nombre);
                parent.getDatosRegistro().setFechaNacimiento(fechaNacimiento);
                parent.getDatosRegistro().setGenero(genero);
                // Aquí es donde BLL valida TODO
                parent.avanzarPaso("paso2");
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Fecha inválida. Verifique los datos");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        parent.retrocederPaso();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgGenero;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jrbHombre;
    private javax.swing.JRadioButton jrbMujer;
    private javax.swing.JRadioButton jrbOtro;
    private javax.swing.JProgressBar pgbProgreso;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}